# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-06 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160223_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordPressPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Post')),
            ],
            bases=('blog.post',),
        ),
    ]
