# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-21 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('status', models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (2, 'Registered')], default=0)),
                ('extra_object_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomKit',
            fields=[
                ('kit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book_list.Kit')),
                ('origin', models.CharField(blank=True, help_text='Brief description of where this kit came from', max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('book_list.kit',),
        ),
        migrations.CreateModel(
            name='OrageneKit',
            fields=[
                ('kit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book_list.Kit')),
                ('tube_barcode', models.CharField(max_length=14)),
                ('work_order', models.PositiveIntegerField(blank=True, null=True)),
                ('part_number', models.CharField(blank=True, max_length=64, null=True)),
                ('lot_number', models.CharField(blank=True, max_length=64, null=True)),
                ('box_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tray_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('package_barcode', models.CharField(blank=True, max_length=14, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('book_list.kit',),
        ),
        migrations.AddField(
            model_name='kit',
            name='extra_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='kit',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_book_list.kit_set+', to='contenttypes.ContentType'),
        ),
        migrations.AlterUniqueTogether(
            name='kit',
            unique_together=set([('extra_content_type', 'extra_object_id')]),
        ),
    ]
